//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MailCenterEntities : DbContext
    {
        public MailCenterEntities()
            : base("name=MailCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TM_SYSTEM_ADMIN> TM_SYSTEM_ADMIN { get; set; }
        public DbSet<TT_MAIL_WIP> TT_MAIL_WIP { get; set; }
    }
}
