//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PackingChangeEntities : DbContext
    {
        public PackingChangeEntities()
            : base("name=PackingChangeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<td_impact_plant> td_impact_plant { get; set; }
        public DbSet<td_main_data> td_main_data { get; set; }
        public DbSet<td_tell> td_tell { get; set; }
        public DbSet<td_transaction> td_transaction { get; set; }
        public DbSet<tm_action> tm_action { get; set; }
        public DbSet<tm_plant> tm_plant { get; set; }
        public DbSet<tm_status> tm_status { get; set; }
        public DbSet<tm_sys_group> tm_sys_group { get; set; }
        public DbSet<tm_sys_group_user> tm_sys_group_user { get; set; }
        public DbSet<tm_sys_user> tm_sys_user { get; set; }
        public DbSet<tm_sys_utype> tm_sys_utype { get; set; }
        public DbSet<tm_user_level> tm_user_level { get; set; }
        public DbSet<td_feedback> td_feedback { get; set; }
        public DbSet<V_Tran> V_Tran { get; set; }
        public DbSet<tm_concern_group> tm_concern_group { get; set; }
        public DbSet<tm_sys_concern_group> tm_sys_concern_group { get; set; }
        public DbSet<td_temp_concern> td_temp_concern { get; set; }
        public DbSet<td_files> td_files { get; set; }
        public DbSet<V_ConcernGroup> V_ConcernGroup { get; set; }
        public DbSet<V_ShowConcern> V_ShowConcern { get; set; }
        public DbSet<V_ShowFB> V_ShowFB { get; set; }
        public DbSet<V_ShowTran> V_ShowTran { get; set; }
        public DbSet<td_salecs> td_salecs { get; set; }
        public DbSet<tm_init_tag> tm_init_tag { get; set; }
        public DbSet<td_pack_std> td_pack_std { get; set; }
        public DbSet<V_ShowPack> V_ShowPack { get; set; }
        public DbSet<td_item_list> td_item_list { get; set; }
        public DbSet<V_TNC_Group> V_TNC_Group { get; set; }
        public DbSet<V_Tran1> V_Tran1 { get; set; }
        public DbSet<V_Report> V_Report { get; set; }
        public DbSet<V_Tran2> V_Tran2 { get; set; }
        public DbSet<V_Tran3> V_Tran3 { get; set; }
    }
}
