//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCREntities : DbContext
    {
        public PCREntities()
            : base("name=PCREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PCR_GCode> PCR_GCode { get; set; }
        public DbSet<PCR_Customer> PCR_Customer { get; set; }
        public DbSet<v_pcr_main> v_pcr_main { get; set; }
    }
}
