//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_files
    {
        public string gpcode { get; set; }
        public string year { get; set; }
        public int runno { get; set; }
        public string filename { get; set; }
        public string path { get; set; }
        public string upload_by { get; set; }
        public System.DateTime upload_dt { get; set; }
        public Nullable<System.DateTime> delete_dt { get; set; }
    
        public virtual td_main_data td_main_data { get; set; }
    }
}
