//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_main_data
    {
        public td_main_data()
        {
            this.td_impact_plant = new HashSet<td_impact_plant>();
            this.td_tell = new HashSet<td_tell>();
            this.td_transaction = new HashSet<td_transaction>();
            this.td_temp_concern = new HashSet<td_temp_concern>();
            this.td_files = new HashSet<td_files>();
            this.td_salecs = new HashSet<td_salecs>();
            this.td_pack_std = new HashSet<td_pack_std>();
            this.td_feedback = new HashSet<td_feedback>();
            this.td_item_list = new HashSet<td_item_list>();
        }
    
        public string gpcode { get; set; }
        public string year { get; set; }
        public int runno { get; set; }
        public string chage_type { get; set; }
        public string change_detail { get; set; }
        public string condition_current { get; set; }
        public string condition_new { get; set; }
        public string reason { get; set; }
        public System.DateTime expected_dt { get; set; }
        public string request_by { get; set; }
        public string production_type { get; set; }
        public Nullable<bool> system_update { get; set; }
        public int issue_group { get; set; }
        public System.DateTime request_date { get; set; }
    
        public virtual ICollection<td_impact_plant> td_impact_plant { get; set; }
        public virtual ICollection<td_tell> td_tell { get; set; }
        public virtual ICollection<td_transaction> td_transaction { get; set; }
        public virtual ICollection<td_temp_concern> td_temp_concern { get; set; }
        public virtual ICollection<td_files> td_files { get; set; }
        public virtual ICollection<td_salecs> td_salecs { get; set; }
        public virtual ICollection<td_pack_std> td_pack_std { get; set; }
        public virtual ICollection<td_feedback> td_feedback { get; set; }
        public virtual ICollection<td_item_list> td_item_list { get; set; }
    }
}
