//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_salecs
    {
        public string gpcode { get; set; }
        public string year { get; set; }
        public int runno { get; set; }
        public string actor { get; set; }
        public bool pack_std_need { get; set; }
        public bool pack_std_noneed { get; set; }
        public string cust_need { get; set; }
        public string cust_noneed { get; set; }
        public byte init_tag_id { get; set; }
        public string frequency { get; set; }
    
        public virtual td_main_data td_main_data { get; set; }
        public virtual tm_init_tag tm_init_tag { get; set; }
    }
}
