//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_action
    {
        public tm_action()
        {
            this.td_transaction = new HashSet<td_transaction>();
        }
    
        public string act_id { get; set; }
        public string act_name { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<td_transaction> td_transaction { get; set; }
    }
}
