//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_plant
    {
        public tm_plant()
        {
            this.tm_sys_group = new HashSet<tm_sys_group>();
        }
    
        public string plant_code { get; set; }
        public string plant_name { get; set; }
        public System.DateTime update_dt { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<tm_sys_group> tm_sys_group { get; set; }
    }
}
