//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_sys_group
    {
        public tm_sys_group()
        {
            this.tm_sys_group_user = new HashSet<tm_sys_group_user>();
        }
    
        public string sys_group_code { get; set; }
        public string sys_group_name { get; set; }
        public string plant_code { get; set; }
        public System.DateTime update_dt { get; set; }
        public int group_respond { get; set; }
        public string group_type { get; set; }
    
        public virtual tm_plant tm_plant { get; set; }
        public virtual ICollection<tm_sys_group_user> tm_sys_group_user { get; set; }
    }
}
