//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pcr_main
    {
        public string state_name { get; set; }
        public string status_name { get; set; }
        public string type_name { get; set; }
        public string group_name { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public int id { get; set; }
        public string pcr_id { get; set; }
        public string issuer { get; set; }
        public string issue_group { get; set; }
        public string issue_tel { get; set; }
        public Nullable<System.DateTime> issued_date { get; set; }
        public Nullable<System.DateTime> expected_date { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<byte> class_type { get; set; }
        public Nullable<byte> app_type { get; set; }
        public Nullable<byte> std_req { get; set; }
        public string std_txt { get; set; }
        public Nullable<int> pcr_type { get; set; }
        public string change_txt { get; set; }
        public string reason_txt { get; set; }
        public Nullable<byte> status_id { get; set; }
        public Nullable<byte> state_id { get; set; }
        public string item_attach { get; set; }
        public string folder_no { get; set; }
        public string item_no { get; set; }
        public string cust_no { get; set; }
        public string issue_dept { get; set; }
        public string issue_div { get; set; }
        public string email { get; set; }
    }
}
