//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Report
    {
        public string id { get; set; }
        public string gpcode { get; set; }
        public string year { get; set; }
        public int runno { get; set; }
        public string status_name { get; set; }
        public int issue_group { get; set; }
        public System.DateTime request_date { get; set; }
        public string change_detail { get; set; }
        public string chage_type { get; set; }
        public System.DateTime act_dt { get; set; }
        public Nullable<int> DiffDate { get; set; }
        public string group_name { get; set; }
    }
}
