//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ShowPack
    {
        public string gpcode { get; set; }
        public string year { get; set; }
        public int runno { get; set; }
        public byte series { get; set; }
        public string cust_no { get; set; }
        public string pack_file { get; set; }
        public string status { get; set; }
        public System.DateTime submit_dt { get; set; }
        public string reason { get; set; }
        public int issue_org { get; set; }
        public string cust_name { get; set; }
    }
}
