//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingChange1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ShowFB
    {
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public string status_name { get; set; }
        public string comment { get; set; }
        public System.DateTime act_dt { get; set; }
        public string gpcode { get; set; }
        public string year { get; set; }
        public int runno { get; set; }
        public byte status_id { get; set; }
        public byte lv_id { get; set; }
        public int org_id { get; set; }
    }
}
