//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKCRemindPKSTD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pack_std_qa_sale
    {
        public string gpcode { get; set; }
        public string year { get; set; }
        public int runno { get; set; }
        public string status { get; set; }
        public int qa { get; set; }
        public Nullable<int> sale { get; set; }
        public string change_detail { get; set; }
    }
}
