//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKCRemindEmail
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PackingChangeEntities : DbContext
    {
        public PackingChangeEntities()
            : base("name=PackingChangeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<td_main_data> td_main_data { get; set; }
        public DbSet<td_transaction> td_transaction { get; set; }
        public DbSet<tm_status> tm_status { get; set; }
    }
}
