//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKCRemindEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_main_data
    {
        public td_main_data()
        {
            this.td_transaction = new HashSet<td_transaction>();
        }
    
        public string gpcode { get; set; }
        public string year { get; set; }
        public int runno { get; set; }
        public string chage_type { get; set; }
        public string change_detail { get; set; }
        public string condition_current { get; set; }
        public string condition_new { get; set; }
        public string reason { get; set; }
        public System.DateTime expected_dt { get; set; }
        public string request_by { get; set; }
        public string production_type { get; set; }
        public Nullable<bool> system_update { get; set; }
        public int issue_group { get; set; }
        public System.DateTime request_date { get; set; }
    
        public virtual ICollection<td_transaction> td_transaction { get; set; }
    }
}
